version: '2'

services:
  elasticsearch:
    build: config/elastic/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - docker_lr
  
  # RabbitMQ
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.0
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin
    networks:
      - docker_lr
  
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app/libreread.db:/opt/LibreRead/app/libreread.db
      - ./uploads:/opt/LibreRead/app/uploads
      - ./uploads/images:/opt/LibreRead/app/uploads/images
    links:
      - rabbit
      - worker
    networks:
      - docker_lr
    depends_on:
      - elasticsearch
      - rabbit

  # Celery worker
  worker:
    build: .
    command: celery -A app.celery worker --loglevel=info
    user: nobody
    links:
      - rabbit
    networks:
      - docker_lr
    depends_on:
      - rabbit

networks:
  docker_lr:
    driver: bridge
