version: '2'

services:
  elasticsearch:
    build: config/elastic/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
